apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: weather-app
  namespace: flux-system
resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
