apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weather-app
  namespace: flux-system
spec:
  targetNamespace: weather-app
  interval: 1m0s
  path: "./apps/weather-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster