apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-test
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/storage/nfs-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default  