apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mongodb
  namespace: mongodb
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - mongo-express-deployment.yaml
  - mongo-express-service.yaml