apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  targetNamespace: mongodb
  interval: 1m0s
  path: "./infrastructure/databases/mongodb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster