apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: swagger-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./infrastructure/swagger-api"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster