apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: otel-test
spec:
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ghcr.io/jaysuzi5/api.login:v0.1.1
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-elastic.elasticsearch.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_SERVICE_NAME
          value: "api.login"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: APP_LOG_LEVEL
          value: "INFO"          
        - name: AUTHENTICATION_URL
          value: "http://elastic-otel.applications.svc.cluster.local/authenticate"
