apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: login
  namespace: flux-system
spec:
  targetNamespace: otel-test
  interval: 1m0s
  path: "./apps/api.login"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster