apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: api.login
  ports:
    - name: http
      port: 80
      targetPort: 8080