apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-values
  namespace: elasticsearch
data:
  values.yaml: |
    elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      username: ""
      password: ""
      protocol: "http"

    kibana:
      enabled: false

    apm-server:
      host: "0.0.0.0:8200"
      auth:
        anonymous:
          enabled: true

    output.elasticsearch:
      protocol: "http"
