apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apm-server
  namespace: elasticsearch
spec:
  interval: 1h
  chart:
    spec:
      chart: apm-server
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: apm-values
      valuesKey: values.yaml
