apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-values
  namespace: elasticsearch
data:
  values.yaml: |
    apmServer:
      enabled: true
      config:
        apm-server:
          host: "0.0.0.0:8200"
          ssl:
            enabled: false
          auth:
            secret_token: "${secretToken}" # Ensure this is set via a secret
          output.elasticsearch:
            hosts: ["http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
            username: "${username}"
            password: "${password}"
          otlp:
            enabled: true
            http:
              enabled: true
              host: "0.0.0.0:4318"
            grpc:
              enabled: true
              host: "0.0.0.0:4317"
        setup.kibana:
          host: "http://kibana-kibana.elasticsearch.svc.cluster.local:5601"
    service:
      ports:
        - name: http
          port: 8200
          targetPort: 8200
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP