apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-values
  namespace: elasticsearch
data:
  values.yaml: |
    apmServer:
      enabled: true
      config:
        apm-server:
          host: "0.0.0.0:8200"
          auth:
            secret_token: "your-secret-token"
        output.elasticsearch:
          hosts: ["https://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
          username: "elastic"
          password: "your-password"
        setup.kibana:
          host: "http://kibana-kibana.elasticsearch.svc.cluster.local:5601"
