apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apm-server
  namespace: elasticsearch
spec:
  interval: 1h
  chart:
    spec:
      chart: apm-server
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: apm-values
      valuesKey: values.yaml
  values:
    extraEnvs:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: apm-elasticsearch-secrets
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: apm-elasticsearch-secrets
            key: password
      - name: SECRET_TOKEN
        valueFrom:
          secretKeyRef:
            name: apm-elasticsearch-secrets
            key: secretToken