apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-values
  namespace: elasticsearch
data:
  values.yaml: |
    elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      protocol: "http"

    kibana:
      enabled: true

    apm-server:
      host: "0.0.0.0:8200"
      otlp:
        http:
          enabled: true
          host: "0.0.0.0:8200"
          endpoint: "0.0.0.0:8200"
          secret_token: "${SECRET_TOKEN}"
      rum:
        enabled: false
      secretToken: "${SECRET_TOKEN}"
      
    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      protocol: "http"