apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.1
  env:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: password
  volumes:
    - name: elasticsearch-ca
      secret:
        secretName: elasticsearch-master-certs
  volumeMounts:
    - name: elasticsearch-ca
      mountPath: "/etc/elasticsearch/certs"
      readOnly: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
    
    exporters:
      debug:
        verbosity: detailed
      
      elasticsearch:
        endpoints: ["https://elasticsearch-master:9200"]
        user: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"
        tls:
          ca_file: "/etc/elasticsearch/certs/ca.crt"
        timeout: 60s
        logs_index: "logs-otel-{YYYY.MM.dd}"
        traces_index: "traces-otel-{YYYY.MM.dd}"
        metrics_index: "metrics-otel-{YYYY.MM.dd}"
        mapping:
          mode: "ecs"
    
    service:
      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, elasticsearch]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, elasticsearch]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, elasticsearch]