apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.96.0  # Pin to your version
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      # For traces → APM Server (recommended)
      otlp/elastic:
        endpoint: "http://apm-server.elasticsearch.svc.cluster.local:8200"
        tls:
          insecure: true  # Disable in prod!

      # For logs → Elasticsearch (legacy syntax for v0.96.0)
      elasticsearch/logs:
        endpoints: ["http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
        index: "logs-{YYYY.MM.dd}"  # Only supports a single index

      # For metrics → Elasticsearch (same as logs)
      elasticsearch/metrics:
        endpoints: ["http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
        index: "metrics-{YYYY.MM.dd}"

    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/metrics]  # Metrics to dedicated index
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]  # Traces to APM Server
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/logs]  # Logs to dedicated index