apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-elastic-config
  namespace: elasticsearch
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      elasticsearch/logs:
        endpoints: ["https://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
        auth:
          user: ${ELASTIC_USER}
          password: ${ELASTIC_PASSWORD}
        tls:
          insecure_skip_verify: true  # skip TLS verification
        logs_index: "otel-logs"
      otlphttp:
        endpoint: http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200
        traces_endpoint: http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200/v1/traces
        metrics_endpoint: http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200/v1/metrics
        logs_endpoint: http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200/v1/logs
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/logs]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
  labels:
    app: otel-collector-elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-elastic
  template:
    metadata:
      labels:
        app: otel-collector-elastic
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.111.0
        command:
        - /otelcol-contrib
        - --config=/conf/otel-config.yaml
        volumeMounts:
        - name: config
          mountPath: /conf
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 4317 # OTLP gRPC
        - containerPort: 4318 # OTLP HTTP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_SERVICE_NAME
          value: otel-collector-elastic
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password          
      volumes:
      - name: config
        configMap:
          name: otel-collector-elastic-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  selector:
    app: otel-collector-elastic
  ports:
  - name: otlp-grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: otlp-http
    protocol: TCP
    port: 4318
    targetPort: 4318
  type: ClusterIP
