apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.97.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      # Elasticsearch Logs Exporter
      elasticsearch/logs:
        endpoints: ["http://elasticsearch-master:9200"]
        index: "logs-{YYYY.MM.dd}"
        
      # Elasticsearch Metrics Exporter
      elasticsearch/metrics:
        endpoints: ["http://elasticsearch-master:9200"]
        index: "metrics-{YYYY.MM.dd}"
        
      # APM Server Trace Exporter
      otlp/elastic:
        endpoint: "http://apm-server.elasticsearch.svc.cluster.local:8200"
        tls:
          insecure: true
    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/metrics]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/logs]