apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.1
  env:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: password
    - name: APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: secretToken
  volumes:
    - name: elasticsearch-ca
      secret:
        secretName: elasticsearch-master-certs
  volumeMounts:
    - name: elasticsearch-ca
      mountPath: "/etc/elasticsearch/certs"
      readOnly: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 10
    
    exporters:
      debug:
        verbosity: detailed
      
      elasticsearch:
        endpoints: ["https://elasticsearch-master:9200"]
        user: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"
        tls:
          ca_file: "/etc/elasticsearch/certs/ca.crt"
        timeout: 60s
        logs_index: "logs-otel"
        traces_index: "traces-otel"
        metrics_index: "metrics-otel"
        mapping:
          mode: "ecs"

      otlphttp:
        endpoint: "http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200"
        tls:
          insecure: true
        headers:
          "Authorization": "Bearer ${APM_SECRET_TOKEN}"
    
    service:
      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]