apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.1
  env:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: password
    - name: APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: apm-elasticsearch-secrets
          key: secretToken
  volumes:
    - name: elasticsearch-ca
      secret:
        secretName: elasticsearch-master-certs
  volumeMounts:
    - name: elasticsearch-ca
      mountPath: "/etc/elasticsearch/certs"
      readOnly: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
    
    exporters:
      debug:
        verbosity: detailed
      
      elasticsearch/logs:
        endpoints: ["https://elasticsearch-master:9200"]
        logs_index: "logs-test-new"
        user: "${ELASTICSEARCH_USERNAME}"
        password: "${ELASTICSEARCH_PASSWORD}"
        tls:
          ca_file: "/etc/elasticsearch/certs/ca.crt"
        timeout: 60s
        mapping:
          mode: "ecs"
      
      otlphttp/apm:
        endpoint: "http://apm-server-apm-server.elasticsearch.svc.cluster.local:8200"
        tls:
          insecure: true
        headers:
          Authorization: "Bearer ${APM_SECRET_TOKEN}"
        traces_endpoint: "/v1/traces"
        metrics_endpoint: "/v1/metrics"
        timeout: 30s
    
    service:
      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/apm]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/apm]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, elasticsearch/logs]