apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-elastic
  namespace: elasticsearch
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.96.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      # For traces → APM Server
      otlp/elastic:
        endpoint: "http://apm-server.elasticsearch.svc.cluster.local:8200"
        tls:
          insecure: true

      # For logs/metrics → Elasticsearch
      elasticsearch:
        endpoints: ["http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"]
        logs:
          index: "logs-{YYYY.MM.dd}"
        traces:
          index: "traces-{YYYY.MM.dd}"  # Optional, if not using APM Server
        # Optional: Add auth if needed
        # auth:
        #   username: "elastic"
        #   password: "${ELASTIC_PASSWORD}"

    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]  # Metrics use the default index
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]   # Traces to APM Server
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]  # Logs to Elasticsearch