apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-values
  namespace: elasticsearch
data:
  values.yaml: |
    replicas: 2

    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi

    persistence:
      enabled: true

    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: false
        xpack.security.transport.ssl.enabled: false
        xpack.security.http.ssl.enabled: false
        xpack.security.transport.ssl.enabled: false
        network.host: 0.0.0.0
        http.port: 9200