apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-values
  namespace: elasticsearch
data:
  values.yaml: |
    replicas: 2

    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi

    persistence:
      enabled: true

    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"

    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true

