apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elasticsearch
  values:
    replicas: 1

    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: false
        xpack.security.transport.ssl.enabled: false
        node.store.allow_mmap: false

    esJavaOpts: "-Xms512m -Xmx512m"

    secret:
      enabled: false

    security:
      authentication:
        enabled: false

    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"

    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi
