apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: elasticsearch-values
      valuesKey: values.yaml
