apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-values
  namespace: elasticsearch
data:
  values.yaml: |
    elasticsearch:
      hosts:
        - http://elasticsearch-master:9200
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-client
      size: 5Gi
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
 