apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  interval: 1h
  chart:
    spec:
      chart: kibana
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: kibana-values
      valuesKey: values.yaml
