elasticsearchHosts: "http://elasticsearch-master:9200"

service:
  type: NodePort
  nodePort: 31601

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  size: 5Gi

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
