elasticsearch:
  hosts:
    - https://elasticsearch-master:9200
  auth:
    enabled: true
    existingSecret: elastic-credentials
  ssl:
    verificationMode: none
service:
  type: NodePort
  nodePort: 31601
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  size: 5Gi
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"