apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-homelab-hub
  namespace: postgresql-homelab-hub
spec:
  instances: 3
  storage:
    storageClass: "nfs-client"
    size: 10Gi
  superuserSecret:
    name: postgresql-cluster-superuser    
  bootstrap:
    initdb:
      database: homelab-hub
      owner: jcurtis
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster-external
  namespace: postgresql-homelab-hub
  labels:
    app: postgresql-cluster
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgresql-homelab-hub
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30002
      protocol: TCP