apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-pvc
  namespace: splunk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
