apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: splunk
spec:
  selector:
    app: splunk
  type: NodePort
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: hec
      port: 8088
      targetPort: 8088
      nodePort: 30088
