apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pvc-demo-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nginx-pvc-demo-storage
  nfs:
    server: 192.168.86.210
    path: "/volume2/k8s-data/nginx-pvc-demo-storage"    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-demo-storage
  namespace: default
spec: 
  accessModes:
    - ReadWriteMany
  storageClassName: nginx-pvc-demo-storage
  resources:
    requests:
      storage: 100Mi      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc-demo
  template:
    metadata:
      labels:
        app: nginx-pvc-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-pvc-demo-storage
      volumes:
      - name: nginx-pvc-demo-storage
        persistentVolumeClaim:
          claimName: nginx-pvc-demo-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pvc-demo-service
  namespace: default
spec:
  selector:
    app: nginx-pvc-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
