apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster-external
  namespace: postgresql-backstage
  labels:
    app: postgresql-cluster
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgresql-backstage
    cnpg.io/instanceRole: primary 
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
      protocol: TCP
