apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  interval: 1m0s
  path: "./infrastructure/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster