apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-elasticsearch
  template:
    metadata:
      labels:
        app: otel-collector-elasticsearch
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args:
            - --config=/conf/otel-collector.yaml
          env:
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: elastic-certificates
              mountPath: /certs
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe: null
          readinessProbe: null
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
        - name: elastic-certificates
          secret:
            secretName: elastic-certificates
            defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: elasticsearch
data:
  otel-collector.yaml: |
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
        path: "/health"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
    exporters:
      otlp:
        endpoint: "apm-server-apm-server:8200"
        tls:
          ca_file: "/certs/ca.crt"
          insecure_skip_verify: true
        compression: gzip
        keepalive:
          time: 10s
          timeout: 5s
          permit_without_stream: true
    service:
      telemetry:
        logs:
          level: debug
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-elasticsearch
  namespace: elasticsearch
spec:
  selector:
    app: otel-collector-elasticsearch
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      protocol: TCP
    - name: health
      port: 13133
      protocol: TCP
  type: ClusterIP