apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      k8s_cluster:
        collection_interval: 10s
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers: [otlp, k8s_cluster]
          processors: [batch]
          exporters: [prometheus, debug]