apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      splunk_hec:
        token: "${SPLUNK_HEC_TOKEN}"  # Secret or env var
        endpoint: "http://splunk.splunk.svc.cluster.local:8088/services/collector"
        source: "otel"
        sourcetype: "_json"
        index: "main"
        insecure_skip_verify: true

    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [splunk_hec]
