apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317" 
        tls:
          insecure: true
    service:
      telemetry:
        metrics:
          level: detailed  # Enable detailed self-metrics
          address: "0.0.0.0:8889"  # Separate port for self-metrics
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]