apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.45.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  install:
    createNamespace: true
  values: {}
