metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  install:
    createNamespace: true
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.45.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
