apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
  namespace: kafka
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9094
      targetPort: 9092
