global:
  storageClass: "nfs-client"

kraft:
  enabled: true
  logRetentionHours: 168  # 7 days

controllerReplicaCount: 3
processRoles: "controller,broker"

persistence:
  enabled: true
  storageClass: "nfs-client"
  size: 20Gi
  accessModes:
    - ReadWriteOnce

auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  saslMechanisms: ["PLAIN"]
  saslAllowedMechanisms: ["PLAIN"]
  existingSecret: "kafka-user-credentials"
  usernameKey: "username"
  passwordKey: "password"

kraftConfigOverrides:
  advertised.listeners: "CLIENT://kafka.kafka.svc.cluster.local:9092,CONTROLLER://kafka-controller-headless.kafka.svc.cluster.local:9093"
  listener.security.protocol.map: "CONTROLLER:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT"
  listeners: "CLIENT://:9092,CONTROLLER://:9093"
  inter.broker.listener.name: "CLIENT"

resources:
  requests:
    memory: 2Gi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 2000m

controller:
  quorum:
    electionTimeoutMs: 10000
    fetchTimeoutMs: 10000

service:
  type: ClusterIP
  ports:
    client: 9092
    internal: 9094
    controller: 9093

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: ["kafka"]
        topologyKey: kubernetes.io/hostname

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring