global:
  storageClass: "nfs-client"

controller:
  replicaCount: 1
  resources:
    requests:
      memory: 1024Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: 750m
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 6Gi

kraft:
  enabled: true
  logRetentionHours: 168

listeners:
  client:
    protocol: PLAINTEXT
    name: PLAINTEXT
    port: 9092
  controller:
    protocol: PLAINTEXT
    name: CONTROLLER
    port: 9093

# metrics:
#   jmx:
#     enabled: true
#     kafkaJmxPort: 5555
#   serviceMonitor:
#     enabled: true
#     namespace: "monitoring"
#   prometheusRule:
#     enabled: true
#     namespace: "monitoring"

