apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-collector
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-collector
  template:
    metadata:
      labels:
        app: weather-collector
    spec:
      restartPolicy: Always
      containers:
        - name: weather-collector
          image: ghcr.io/jaysuzi5/weather-collector:v0.3.2
          command:
            - "opentelemetry-instrument"
            - "--logs_exporter"
            - "otlp"
            - "--traces_exporter"
            - "otlp"
            - "python"
            - "/app/src/weather-collector.py"
          envFrom:
            - configMapRef:
                name: weather-config
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-collector.monitoring.svc.cluster.local:4318"  # Use HTTP
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_LOG_LEVEL
              value: "debug"  # Enable debug logging for OTEL SDK
            - name: PYTHONUNBUFFERED
              value: "1"  # Ensure unbuffered output
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-secrets
                  key: OPENWEATHER_API_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: weather-secrets
                  key: POSTGRES_USER
            - name: LATITUDE
              valueFrom:
                secretKeyRef:
                  name: weather-secrets
                  key: LATITUDE
            - name: LONGITUDE
              valueFrom:
                secretKeyRef:
                  name: weather-secrets
                  key: LONGITUDE
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config