apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.33.0"  # specify a version
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    manager:
      image:
        tag: "0.93.1"  # matches operator version
  targetNamespace: opentelemetry-operator-system