apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.44.0"  # specify a version
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values: {} 