apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-credentials
  namespace: otel-test
spec:
  encryptedData:
    password: AgBxWKdnr1xsL61HsPch06OYWf9eKe6CEF5z0gtUjAkmbRiG11kq1DrIQU9jJt6bscuagpDbWEwV6dCusnosA2zH+DKX9SuBnDogCriY6/P8iGdyEIT/2lzDXLmZD08YpqAn8735M9r4VBMMYvC2APfg/5VYaR6DWceYZdWyqHCbP45r3ufjV74Txuhr4iSZmoo4R4fwYxPro+80L8coSNfBXu0DtT45tB9Pda6+WVgSHLJW+x6oeNGm1fT40Li2UjDJP70zVte0JP2ahAC0Dwt7dBMxTbvXRKdf6PYZwikPRrceUtPwrDN9RXCsLtx5Q/PwYmHBoSFGCvyjpwHRt+0Zo3NIaN9SxWH+PFgQKvAaPgU7KkclwWa0CT5iEDPffi58LjBgrnMUjTBBlv4m3SyZYLgUkKpO7v07jBYG3TjoRwWTDPTnnXYvSkyb8QjCRIwdKZQACvHmcSGcFzmxktiUkbJwaj9h3ynN0VA9wPar/bZ8CN86wtCa6b9xvIxkxfjNazPyl3QsjlLKFZOSq3g8Jgw3uGJ9j5lrEPB3nPJV9ZlCbTCfSfIMbKRM53s9ne1jIchjzpSMjrqzqMxkllqUXDUeZoIRn13TbD7UdVfloW1voSz8ri7YZR9zCAxQlcBcoANOBVkRHKu4yuvH3M9tihrmIdNWkwVBrB1AyTljy+F4Hi46y9MUQNh6NNp74kpXki4B+zx1rw==
    username: AgAvbJcfHTNJmxY7ZmKOf+bHtabmd6gzscoSN1z5dgBXnJ6bgj54zzhXfH4PEHpKGaEm9QLEOBRqfnhcZjU4k3AWov268KURm7dDDRddyviZCRuXXCCoGdisnQ/0xHOMIAPAdlVq2QJCbDH/e5a2F/xZ5p+o1AyQwkjDR4BgaePHJFJkdmfVxFaZW/JTwahNUxCTMS9aD9Q3u/dqy7nA4JikjrNZnt5JH02286nzEzeQoSmLnQrMbfW3GIpcABga0n/lWBSrKBZReYZYul3im8s4dEaQu1BUOjWQoGt81q0PGjgTTLwopFYFCl4YaG9FHO2RO+sfoijzrbmvTphMBqKYTvT6QWhHBHb9mDD5mbnPa36OI+98HJzP5O75pRWo60kWXNWr0FzJ8fmfL2yBhdXoI8RF2b+H/TI0P5rBxKMC7sIsvJVmviYShBuIgGw1QBCq7k3vSlyquzCpEaO9yfIjUOpmyqoGhaOOJCggCzFSmFK5nLvCtSpP39F3cB0/1zz12QDM8xgSpCa8mHS1f8mb7naZa+Bfc4hLhstrGs2hnBq05X9LSGcLyk3ybkMW/EE+iVy1yOSlWw2ehichLIBB0c72AjZ3NEmTd17dnkR1b7CQAmvOOqGtuxiRImJ130DY3OXFfT9mnYNAPhJGwpSBCdPV0rGn/LKNCbJ06r7Bw38ULJKNDhOK6cb5yJ27hiOAlabE2Q==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-credentials
      namespace: otel-test
    type: Opaque