apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: enphase-collector
  namespace: flux-system
spec:
  targetNamespace: collector
  interval: 1m0s
  path: "./apps/emporia-collector"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster