apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: collector
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: collector
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: collector
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
