apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/certmanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
