apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBGDSDMZHHiKGXsWQfEbNvuCif6qWvaW2NBvQcXi5OV/8eriWzcaQzR6gQMPVRMiXTC3C2nzKfwo5+4vgDAK4EmyITd++EPI2GRjsoCYc2vZGT6RkwRyyPDjR0Z/RNz0TAY0zvseqHWIgal1HTHGrlPMK4GYz19FK75XVGIAnJuqyv5S6taH9p01iXohhMiUkdFSnqZFpvCmpGqmx6eV2TFZheTxKHQdjdqYGLmo7/tT0zKh4IQajvRiPvbsS9A9yc9+LGEb3+kg6UhxNm85RrFDLa5E08U6VN5yzcLl+MHLgdvY3cmk5D0vKkhKMpsqjxlqyLPaujcDkTrgbS18SYVWOL0EmjPZ+86CoU+srVAEqgwWRpKaWb6bvVQPq8040SZncxurNSK43OervlVyih8qQk+AgRQ4zBuAtMVy5QKW9p3ci7lXW5M3SigOPxKXts8fuWaY3iHxn6iiV678tXM+EUBRzgvIfA01dbmFpiyVHwdGM6iJPa+ZKas6/cal1EDzGSMH4xjhI5INICZx1E4K+SRJARincnZ3ZNlQ7q6ZmBbun5sDyhuIKDJfCNNfWxIa9dBJ1WIUL6pUV/p90gkb95ajo/VEW9tT32xwfFAzsekjmuq284q0H1O5QLPbS6OnKvXKaEmUerrM0/R8Mb+F+5a/6Z4KqGMW8p910ob/LQ/OYS/AtH41QCa8FJJocac1io8kR3aoANIaVlY
    POSTGRES_USER: AgAI5Xc+oCXQf1Ds0NGYopt5crzaHMXhkLtEPXvpSoUdtpRgjj2G+WbV39xChraGdp1IBXBlPmV7LYLLISkHUQNihvCv8oUDJ4j1OxZom9obYGbNfQJ2ISqUJIfSC5bUppSjKKuv8C6oqmqTqMFhZsc86E8dxwxU7kRREgsn4cjXLh9Sl8tsLgaHwpJFExAmUW1QbJxDUGmS1pJFpqwIuowP4dHi7+cl4Sv9ea8GymZ+ndenlpHSFgI6iIr5I50Dl3+BF1l52h10oQzXsEz8NyFcS8SwcfzQFs0MXYoaX0ceIj1UBhGt3ypQLoX/5UA9lePnwU2aWicOlUI5cJD9LorB8FD7rDZFyL/9H4oZ9vJ7cpA5/RxoOrWIAQVKQhiwatGET6B+1BqXc30X/RV1UBPcpZg2sLiqIoDEbMbwsdvYapaM5NEkgV3fxHQPVYDnDuS30WDv83LXEOMAfKThQLnPge2M0ATCMoQLOtU7XhbBFm7SN6FGQXreLrSPzjwU5AAk615EJghl3Z8nXzQZchxuFTwUlEAU1klmm8OXgIy+18yM2NvTeZ03P4pEhNWTLXAmae+FCQEqtxtx8HfZy87kXTOFcCiIcvNNdpHkBHqtqiKGTta8rUTMVAu34kFMh12E/vDIuxkp51AzzIenqPIsZC2pFrCMCYeYZRR7+nBrcGla566tgbrHWbifRDPathlMRFmYXMTT
  template:
    metadata:
      creationTimestamp: null
      name: backstage-secrets
      namespace: backstage
    type: Opaque