# Backstage Helm values for local install using external PostgreSQL
namespaceOverride: backstage

app:
  baseUrl: http://backstage.local:7007

ingress:
  enabled: false

postgresql:
  enabled: false

externalDatabase:
  host: 192.168.86.200
  port: 30001
  user:
    secretRef:
      name: backstage-secrets
      key: POSTGRES_USER
  password:
    secretRef:
      name: backstage-secrets
      key: POSTGRES_PASSWORD
  database: backstage  # use the name of the DB you created in PostgreSQL

extraEnvVars:
  - name: PGSSLMODE
    value: "disable"  # If your DB doesn't use SSL

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
