apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-config
  namespace: homelab-hub
data:
  DB_NAME: "homelab-hub"
  DB_HOST: "192.168.86.200"
  DB_PORT: "30002"
  SPLUNK_HOST: "splunk.home"
  SPLUNK_PORT: "8089"
  NETWORK_URL: "http://network.dev.svc.cluster.local:5001/api/v1/network?page=1&limit=1"
  ENPHASE_API_SEARCH_URL: "http://enphase.dev.svc.cluster.local:5001/api/v1/enphase/summary"
  EMPORIA_API_SEARCH_URL: "http://emporia.dev.svc.cluster.local:5001/api/v1/emporia/search"
  DARTS_URL: "http://darts.dev.svc.cluster.local:5001/api/v1/darts?page=1&limit=1000"
  SYNOLOGY_URL: "http://synology.dev.svc.cluster.local:5001/api/v1/synology?page=1&limit=1"
  WEATHER_URL: "http://weather.dev.svc.cluster.local:5001/api/v1/weather?page=1&limit=1"
  FORECAST_URL: "http://forecast.dev.svc.cluster.local:5001/api/v1/forecast/latest"
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "django.home.lab,127.0.0.1,localhost"