apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homelab-hub
  namespace: flux-system
resources:
  - namespace.yaml
  - secrets.yaml
  - roles.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml  
  - ingress.yaml

