apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.6.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      enabled: true
    grafana:
      enabled: true
    alertmanager:
      enabled: false