apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elastic-credentials
  namespace: elastic
spec:
  encryptedData:
    password: AgCvLuLV8pbnzw5mfEBCOYH6bmyECAvFdonn+2anGcuIIrBvJsjQ8q37cKlQszF5qjZiS5rALeSw5ELgQKcb/6XGJEHPHCJNaoTpNfp17H7hXWdfnS7hMnv+jzfHp23zz4eNVQ8twfTod9L86/pgfM0m57qjxbFBey210VYJL920FJYIZCtg3tMzi43mosLbJHwwoEs8wYUldj3TX5M/zgi47mauWBeErZnzlMf4Wio4h4/pLwmM363xXdnp6QYtlDUoddk3KMajooYBMql7goxxxLd0Cn11Kqtd9Agnl/pyer26g9uoY3bpIhE+2hCBDuOEnM5vJv0Zhrivhe+rIBVujzYUxDACnwu4+QQ3qnU8rQJh0JVp2RzjoXgB3xOhZri7KZdJ4NcO34gwo5v2jSuSK8VzjWkolAVG3NFwuk124s3qZuZMRCAxpOWT5XMBK4hwbyzOtGcfLQup0Suf6lKOduADj2sX0CjKVEwbhH00ODcReBkAIxFUQ9XK5fU7vyhMcAGEgBh9RtIISvHKY9dqMYXOvwhHjBBi4FPWjx8kLQeQZi4Miai6C5BJgvnjG0KS2jOLJ/VgAiVIps4yZeVMywk5sA0kEVSejgD74Mh/GdzA7xxznYkBSEvxqBu/eL0CteOfJf8ejjEIdK7u1+ZjXD6dfaWPM8BQQyTvcMjVBZxfDva2gx/4X0vTys/iCrMTr4LjMuQC2NkAEPTv
    username: AgBQQvfm634DBMjQm9RXycwYkFmoX3U6cT+zqjvpV02RUZ248MgvUoH0r3qu2HLcUK/9satvpiHnfSzHt6PT13mt6ghNdEYh7+UIy1MC1HtYrK+obTuoiM096zigo6/2SBIwqZhLKXIa8r1T684gOKc+7T9l7YbmQ+1GDjrICptqag1cvKSkSnFRa/MaBIkkdX863YXsMFbi6DQYSRbDSYXgdIDKWGz2U4xeCEyRuFu1zX9chKK1mAuW3Jaf73a7xfOZ89kPSrSPhl4XDJpMKqUHxHT6OHM0OsB3i0e4dtq1sNeBZroB7LbA4C34/o0DKYyBkL+2XuCzDzlgneToAF3lXci87rQvFXk1kynDubSsUv6VjvYSyvIZ14zqdosUC3LJfdJg1PNZNaG5EniX6unWPGp///9+nCEwgQIXDJSvY5W+ivUWCRFbCnUK5FMZ3DFAe6x7EthXynW70nIzI82HuNJYsBMrAwNV7e/p8ubq92/DttYD9rufbS8D+SFROIgYtmFPa4x3Nc3CnO765+yaCubN6AU7L+EhZEYwaDHAzcxDRFoXXc0pgF9c393CgCua+SQaZAtroqkyFbyjx6N5nfnb+mQ7e5JoZMuOf00cces1rBakQtwgKykmF36633jmoieTb9fm/PAlr6CGm0Vk/hPUF7vZU315YP+lKL3W0aIpTXtFmKN9t8r9/aVe0pX6lKcLzcFT
  template:
    metadata:
      creationTimestamp: null
      name: elastic-credentials
      namespace: elastic
