apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: 7.17.3
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 1m
  values:
    imageTag: "7.17.3"
    elasticsearchHosts: "https://elasticsearch-master:9200"
    service:
      type: LoadBalancer
      loadBalancerIP: "" # Let MetalLB assign an IP automatically
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    secretMounts:
      - name: kibana-certificates
        secretName: kibana-certificates
        path: /usr/share/kibana/config/certs
    kibanaConfig:
      kibana.yml: |
        server.ssl.enabled: true
        server.ssl.key: /usr/share/kibana/config/certs/kibana.key
        server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
        elasticsearch.hosts: ["https://elasticsearch-master:9200"]
        elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
        elasticsearch.ssl.verificationMode: certificate
        xpack.security.encryptionKey: "something_at_least_32_characters_long"
    extraEnvs:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password