# prometheus-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ui
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: web
      port: 80
      targetPort: 9090
