grafana:
  persistence:
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteMany  
    size: 5Gi  
    retain: true  

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
      - job_name: 'pg-exporter'
        static_configs:
          - targets:
              - 'pg-exporter-prometheus-postgres-exporter.default.svc.cluster.local:9187'
      - job_name: 'otel-collector'
        static_configs:
          - targets: 
              - 'otel-collector-collector-monitoring.monitoring.svc.cluster.local:8888'
              - 'otel-collector-collector-monitoring.monitoring.svc.cluster.local:9464'

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
