grafana:
  persistence:
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteMany  
    size: 5Gi  
    retain: true  

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
