apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-homelab-secret
  namespace: applications
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB4PcxaiL/5lLCdb4cmaOp38nLNbgIoPsR3brGm4BzTxEKlSuofCqd4Cp9C/Sswe8AScs0U0MytV6isrCRyttaO6tEyJMy4O9RPK3elMb8brlt7zl4JW0/s3OT0QH7N9r4/ZzLUhKngbRJNd4qw25dbU3N+34fqb3q6XDCuivka8ObmygXyj4mjXgYCUa9Gf4qiRoNUrMm+k1G7fipWEAzMe5vyVAf/2X6QNfEK6RMufw8SjeOmHl8vSJzj084FWZ67F8FzE+hCcJtCh8yPq0f5LJkCPVgcxb+JfyaGSkGNj3ns3kXZKeC6JpCPVKmBpllMXzQG+6qkmN/3Ed0Fi/tMszkhFBnwM1BhqHdsLO1HSK9pwVdl+Ah37GA8+fkTidkwi1yqvJvydXk0CpBd3m2BOeAm72SRpKFc5rM8bFRkqqIs2S+Cp5uckkOMJoMfXD4BZuQVUUDiwow6oJQKPTgRNY8WG1RbzOZX+OcemvM6gRqNKJ0dWwwogS+65D6CrZDYmPruxxMsB/+4FS/n/5DJ1VPErO+5VuM5R9PlLz9CxEYrxPGit6cXfID+Hri+WKnIIroV15+gnBujDzA5q7lqrbwF3owX2RvPMQDj+S9CCLlmobMMyGGGoypY5CvBOoKM90tEmwxoSxgkrM5HInaQNkMbPA9wzHQ6ddkj7CrDUPYsH+zmr2Rdo94+uQkvXMC3ZKSLS6noEyIOG7KkdR22pzzES7p2EkN40vfC1FzQvULzEKpzDk9Lu3bQIbPRbbAdrdHPygEmQizr93MzDrCF
    POSTGRES_USER: AgAtBOqrhAgT1/LFmm6c+eZWCHgaSDRHXvUQOB9IHMLobNxL+wILTWuXJIHAVlJRwgdWwiAu9EmvB+GG867S6IO/H1zCmExYWo5QhA98Cia5iESQYrsBKuhDyzqNDmXqTMpC+KZpmxrofeEA1ywy/0nPpa3TWKeAKlddLGucV6VC14W/JFVie+snjVikLz54+mmWFbjtzDp2wRLPPOKcHpDB0OTxLE/OODrlPTnxRjCGaZ90b74Y/h7NCqKgMrwbENPKm/v+Uviq1x2x0B8qolZEjs53y6hkY10q8WsdNRMoC1ag1t3fFFiiLpV5aYrzqNmCMLYRMwS3S8kh/0ALhwDkdZ6iafPirqAYk/l87Sq1y3NrJmsvMheHAWm2Q2oiE0bEkxdm7+i0C4I9VKaC3jZr1Hj5p3RcXMbGdNAE3InZb4O9O/NMbf88nmvS2SlL3OuyICmfxkCqUaK7+4FMuOUU/o7J5Y+fV2CAKfw0ARt1iBuAdE57geK4og48qZ0zrBuNv2yWACH/5eyRF/7X5q2noEuABedq7wNO9T/ovDE+mqGub1PsYTOrALXkLtcmy5LTmtq2ow/oKEidncSIORk8zwHjP4iQzleo0ZK0Dv2QkXKxuqk+KsC3GKsyzqmrCo4Zk6mVs2pXQmRFWOpGETizLkJSse+jczYaQG6ghruqBZmGsFOVV7hDGGHgC/r6XPs/pPoclTRf
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-homelab-secret
      namespace: applications
    type: Opaque