apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.96.0
  env:
    - name: SPLUNK_HEC_TOKEN
      valueFrom:
        secretKeyRef:
          name: otel-collector-secrets
          key: SPLUNK_HEC_TOKEN
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    filelog:
      include_paths:
        - /var/log/containers/*jretirewise*.log
        - /var/log/containers/*todo*.log
        - /var/log/containers/*emporia*.log
      exclude_paths:
        - /var/log/containers/*_kube-system_*.log
        - /var/log/containers/*_kube-public_*.log
        - /var/log/containers/*_kube-node-lease_*.log
      multiline_parser:
        type: json
        parse_from: body
      resource_detection:
        enabled: true
    processors:
      batch:
        send_batch_size: 100
        timeout: 10s
      attributes:
        actions:
          - key: environment
            value: production
            action: insert
          - key: cluster
            value: home-lab
            action: insert
      resource_detection:
        detectors:
          - kubernetes      
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      splunk_hec:
        token: "${SPLUNK_HEC_TOKEN}"
        endpoint: "https://splunk.splunk.svc.cluster.local:8088/services/collector"
        source: "otel"
        sourcetype: "otel:logs"
        index: "otel_logging"
        disable_compression: false
        timeout: 10s
        tls:
          insecure_skip_verify: true
      debug:
        verbosity: detailed          
    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
        logs:
          level: "debug"          
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp, filelog]
          processors: [batch, attributes]
          exporters: [splunk_hec, debug]
  volumes:
    - name: splunk-secret
      secret:
        secretName: otel-collector-secrets
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  volumeMounts:
    - name: splunk-secret
      mountPath: /etc/otel/secrets
      readOnly: true          
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-logs
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-logs
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-logs
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: monitoring      