apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.96.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      splunk_hec:
        token_file: "/etc/otel/secrets/SPLUNK_HEC_TOKEN"  # File-based token
        endpoint: "https://splunk.splunk.svc.cluster.local:8088/services/collector"
        source: "otel"
        sourcetype: "otel:logs"
        index: "otel_logging"
        disable_compression: false
        timeout: 10s
        tls:
          insecure_skip_verify: true
      debug:
        verbosity: detailed          
    service:
      telemetry:
        metrics:
          level: detailed
          address: "0.0.0.0:8889"
        logs:
          level: "debug"          
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [splunk_hec, debug]
  podAnnotations:
    sidecar.opentelemetry.io/inject: "true"
    opentelemetry.io/volume-mounts: '{"splunk-secret":{"mountPath":"/etc/otel/secrets","readOnly":true}}'
    opentelemetry.io/volumes: '{"splunk-secret":{"secret":{"secretName":"otel-collector-secrets"}}}'