---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: monitoring
spec:
  encryptedData:
    SPLUNK_HEC_TOKEN: AgA6NSxGehKhU1el32iIlrW20ABHVj6I+SrD9gvgVssDdiCXm0wceSwY4fBasr/eP3VrHd0D9Zp97cLRipXW25ioq4fBhy3k+U/8YHvgcMyJn2DqTFcctsuNLi8qBTfK1Ym1fjgrr7RDbyvkSZONrAr5oc+YEuyESmwC1T+27L0ML9t2jzpI6Vwk6YkYwW9r3u2d5778vI62rHsP9g9Lxt6wiBx5104bnucTvCOdWm1/tZtuwUi8jbLW1wK8ZdL+HlpAQ3Tfu41c4TQi49KYbkC+kxQJybHYiFJ2c5z4rJ6Q9P3/z8SEStQk8LvVxT9Ws0jGWTy81RKI9xRYnNDPhsXfd34CxfFkIKfpBjnLJQa9mzONxZhfdrpo1W6zablyNh3fskj3eAtiHXzy6iWqQuUH3Kl6M9YgCgmW2A8jlJnu1u/L0zhYQk6ijEqEAAgDioXwYLcp6cs/8CTnCDrmWZ4lSBZ+TydzSkEyhxC25pgYJYXHMd7bWt70YKTzOg5NHvNGTyyNLJ/uTOG2dDRQExPvGWxcl2pN9PHl1m6bqm5U9MPc62BH1fkB/pD5LcCmflSqN3FHyhCsMaKITW3Fj8X+9k6Qtpgi0QfZfNun2MKm2DVGD4LamqIORBPkO4BjPv2ktEpw/WI69YM/8lXz36kgAqHi2/qLZIlGddK83b6qtQ/57s1EHcnX0L0aLXDXtw0aXwn+E2CKi6KiGayehfUGWHqaTgk0UGmri3EqqtsAL4OTBbw=
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: monitoring
    type: Opaque
