apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: monitoring
spec:
  encryptedData:
    SPLUNK_HEC_TOKEN: AgC9YEX21U+5AuYSZT5TUw+8pYnGLowKb7j7yEnxyUgJfHrQET1zJRL8hWQ6ECJlNOfgeRl0arxHUBiURWdNLkhBfPQRqhe665ZKQ01Bzk7/of3bJ/EY9QrdrY/rUkWoZcdJ5opVbf5eLfH72KygtoC+dUXDgQHcxiCYxgBVHoceMvUxTEdEaJpbBxeUVFpaP13dxkcq7ZYETvo2BDJpmxa8kn5ULce8PEv/9n0qSvJ6+gCETtZjSGlr2GSYLB4w5fHwlWYlIczs/UU+Vw9THmMdpCm6HJ2HB2MZmjwZPjF0Jlzmev0Jn/u0ujvhvTWIdZTSEHWcBxI+kBoOJvqes301jhbt+cjBOa420pyU/6vcZdwiWyY6p6YZQI2vMZ9/GE82fa9In8DKON3IYGnuTAQsZrROlYC3HSCEWM8kasj+7kUQ4121rVUDxjjzkpAYtt4ZdNjNnnNQd8JHdII/GJ91txKgMs5FloMNqmzb+dinQORnuzNSGJ7d360cZMqRKWWF6x+ySUeVTSFRsWFSlRVsASNA6vmrk1OQ65YhAhzZGUxOSQm7KBfFQ+MNzh1A9Jzi2NU29cE9jjOhZG49n2+HDI3zAUvgkrsovj9ruOvPDFUd74SfEOSIFD3B3tl8Wj25boEcpoWNvls/RSTpSZA8OaQKnhY94sooh/6rfnHKhYC/dRZxpcC/ZKa0SRgeda8xvORzwdSx9tAJlRE1P3Eti9upmu5DwjEWKJKHT7en5T9phn9e
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: monitoring
    type: Opaque