---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: monitoring
spec:
  encryptedData:
    SPLUNK_HEC_TOKEN: AgCW9f5DaHjNy91lqzKaAz31xWs7YEeV3g41Af9r/js2mqYc9clIHUMerdF/iROWDIX1hM+tQs2HQTdESS/RxAPShpSEKhTfM+dMH92xkygc+4kdfF+8vyn08nBJzMF2kaHgQx1Vdr01qVd1H34wPh0NgW/JhOEaWfQ+VB0F3S/HPCjq8y/y59azId8BGTsA/eJQafhGSI5NH5GS/8MWAVV7AQf4xMdTPFNEt1/cXcWNtmlb0myDADSA+g1/UPiF0e7P2a2jVoONeYkHHzWENPkSEGpK6ve78Da+0Cx3X/56jQfSriJLl6mUD6ri8TWvgTjn3XMWSufyza70ZqJ2UvhECMYHQoasLHmndYV3FNBNS4cPhU/RCVsNPc3t0gC4kDN24N6U0lXmiOiEkzn7SMd8UzYW3g+VnCDSPcFpTpGTld8+MdK2c6p6pSzxE6uY4UxzrqZVbjdIVgT79oVRatnNKoA67VB3OoRbCMirNhbtRS1hLZk1vbGb69iPNNbTduEw2ZcsesehMNYd3wOydZ48N9vE0SpB+VFJ279dUZuDfxDUK8eVKm/2aGjzI6h+uUKp8YjmLp1CEquj4sQOpvojWWC+WjeulzhrAG/MBhRU4LQZWYCDkcWpzNRWEDHJYP/yYUU/DEOjxrUhH6fm6ujh+O055hgjN8Pyg4pZgGp8RitRVgoPQ38cufw7ZHzCbWSsbwaOnR41cSLCP+BRtcMhHrcH77tFjLb44Cz2C5d1pmHOIHE=
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: monitoring
    type: Opaque
