---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: monitoring
spec:
  encryptedData:
    SPLUNK_HEC_TOKEN: AgATrlGGFQhTpxHHPsx80DfRAXVBDRwceVhjGFJWb4ywAezyIii1ub1hI8yjpPeh1rs/vQ4kUC6Ds9QiVyNCVvKC4vOGw8oNohViKq6ub4edYkn0DD0evABcuGTTTQLSAbtUW4AINxDObXgE9un7eEvesZZM4hjvpU4B/ngixw9flSuvQtTcyoObJSPwQ/qTjS5xfzEnlAxIU/hiLDRI+s49d0RVTbHv08yJqVWh3WEW81zmJfDvLUwjxo9yMT2JUc/n681zxqq26oqbEyCHXY9sbV5ZEepf22TnKLIb2qGqUdsSHusFNudq/kKqlsvMX/NzljYm35kSjTJmz5vtKcuE4Ri3KNd6+vQYzI3G7tGj2ZNIWcBtDaekDZ1gBr+c+k46EwAfI2iM+BnlhdkQQYANljTO27XtEr3Z54TnfRc5T3uWCUc+PGMXGUr4HWSwWNL+xnNs3WEGAemEFr/PPuLgU80EVR5Yc3iIbgYEEceKvtm+RueZzczu8OwE+3wkPLgceHTL1r3VZHJdx9qOdc3+zrSQ0CV0QGCkiPHsZ0DC56wcUrVHDupPNRWWHQt7eOLXpYhbH9VONTQplvuN5UjBnbPA0aXi4UtHRoznf0SBTFowPOdpHyN1eWN3QMhb41TeJU1ynBx7n1/5yPLmV9pltX8/OX/yv5TWtzNxVc0/ntea0t3Ra5C662iB20rArcWCSrEc8etJG+XcETy3NJ7cEUBhWZNjVXOzo16AYia41lxQUOs=
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: monitoring
    type: Opaque
