---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: monitoring
spec:
  encryptedData:
    SPLUNK_HEC_TOKEN: AgBciWSFI66+eXNL6GkSnWSB+GIByOzXaz0cMnOFIRDYsAp+iy6d7i3CzkY7xAApfNNoc0/fQouerauPdYQkNUD/mlvcj0HZZ7i9PL0txevbgcXnkr/D75NA3Wa22LKCxJjXOwCLUOtb7gpeYGPS7ctsyvut97OYVzK2SLa37+/cqxn6YBwxaDBB3RH2fryzk1fVWY4aWi6pMcM3tDzoy/Sg0WuW5RKY2d3aGz1V/rrMoV3BtCKJvlrgSBTl7LUhM159FLzZX3ZG0gGC/GkjVFYSX5eMahd9MOvr45yYKi5u7ifHIauWgP4xT/ECzfzYRc2/vBtaVhVtbIeFuHZvdsuzjYE1Ih5wSB6dGATYp4K33kAmm8H2SWzqUgkyEoQg9nWhsrKtqAl3tv63jIkv6SEIdJ0jBlF0QRLGcuA0UHfXHqEj4/Pu+N12jyp5UnPkjTfKrod5gb7fRxzZy3qYrc8uuPvVK7/1a7CDDYPtP/R+/daPVdfnnx8w3EsQpBo3NM0FcTEP6DvvfI1U2qogezZAGkKRcSqOVJZIWlttkXqYfyeUuTNuawhNxFRR4ZlsXUxfW2HMfAofcxuLFc4oTwpt7tgRoWn2xprcViggej+5Y6h5S4C/t0d+eci4ULNpFMAblSrkRSwJUM+6MO2TjqKVYIp7lFxQc5uTvpZqDwOp6015s4rEUOv86iWPQYr/HLcyXZ3f6caBXW525m1N2yHlYYlR7/S/Qd25GdUcjDJD6CcqdZx7
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: monitoring
    type: Opaque
