apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  namespace: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-worker1
                      - k8s-worker2
      securityContext:
        fsGroup: 41812
      containers:
        - name: splunk
          image: splunk/splunk:9.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: web
            - containerPort: 8088
              name: hec
            - containerPort: 8089
              name: mgmt
            - containerPort: 9997
              name: forwarder
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-secret
                  key: SPLUNK_PASSWORD
            - name: SPLUNK_HEC_TOKEN
              value: "dev-hec-token"
            - name: SPLUNK_ROLE
              value: "splunk_standalone"
            - name: SPLUNK_LICENSE_URI
              value: "Free"
          volumeMounts:
            - name: splunk-storage
              mountPath: /opt/splunk/var
            - name: splunk-etc
              mountPath: /opt/splunk/etc
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: splunk-storage
          persistentVolumeClaim:
            claimName: splunk-pvc
        - name: splunk-etc
          persistentVolumeClaim:
            claimName: splunk-pvc
