apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: splunk
spec:
  type: LoadBalancer
  selector:
    app: splunk
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: hec
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: mgmt
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: forwarder
      protocol: TCP
      port: 9997
      targetPort: 9997
