apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: otel-test
spec:
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: ghcr.io/jaysuzi5/api.authentication:v0.2.0
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-elastic.elasticsearch.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_SERVICE_NAME
          value: "api.login"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: APP_LOG_LEVEL
          value: "INFO"          
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"
        - name: MEMBER_MANAGEMENT_URL
          value: "http://member.otel-test.svc.cluster.local/members"
        - name: KAFKA_SERVER
          value: "kafka.kafka.svc.cluster.local:9092"