apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: otel-test
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
    - name: http
      port: 80
      targetPort: 8080
      