apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka-ui
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kafka-ui-values
  values:
    env:
      - name: LOG_LEVEL
        value: "INFO"
      - name: KAFKA_CLUSTERS_0_NAME
        value: "kafka-cluster"
      - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
        value: "kafka.kafka.svc.cluster.local:9092"
      - name: KAFKA_CLUSTERS_0_PROPERTIES_DEBUG
        value: "security,metadata,cluster,request"
      - name: KAFKA_CLUSTERS_0_PROPERTIES_DEBUG
        value: "all"    
      - name: KAFKA_USERNAME
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_USERNAME
      - name: KAFKA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_PASSWORD
    kafka:
      clusters:
        - name: kafka-cluster
          bootstrapServers: "kafka.kafka.svc.cluster.local:9092"
          properties:
            security.protocol: SASL_PLAINTEXT 
            sasl.mechanism: PLAIN
            sasl.jaas.config: |
              org.apache.kafka.common.security.plain.PlainLoginModule required
                username="${KAFKA_USERNAME}"
                password="${KAFKA_PASSWORD}";
            request.timeout.ms: 60000
            socket.connection.setup.timeout.max.ms: 60000
            connections.max.idle.ms: 180000
    metrics:
      enabled: true
      kafkaClusterName: "kafka-cluster"