apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka-ui
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
  values:
    env:
    - name: KAFKA_USERNAME
      valueFrom:
        secretKeyRef:
          name: kafka-ui-secret
          key: KAFKA_USERNAME
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kafka-ui-secret
          key: KAFKA_PASSWORD
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: KAFKA_CLUSTERS_0_NAME
      value: "kafka-cluster"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka.kafka.svc.cluster.local:9092"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
      value: "SASL_PLAINTEXT"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
      value: "PLAIN"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
      value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$KAFKA_USERNAME\" password=\"$KAFKA_PASSWORD\";"
    metrics:
      enabled: true
