apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka-ui
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kafka-ui-values
  values:
    env:
      - name: KAFKA_USERNAME
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_USERNAME
      - name: KAFKA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_PASSWORD
