apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka-ui
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kafka-ui-values
  values:
    env:
      - name: LOG_LEVEL
        value: "DEBUG"
      - name: KAFKA_CLUSTERS_0_PROPERTIES_DEBUG
        value: "all"    
      - name: KAFKA_USERNAME
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_USERNAME
      - name: KAFKA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kafka-ui-secret
            key: KAFKA_PASSWORD
    # Add these critical values
    kafka:
      clusters:
        - name: kafka-cluster
          bootstrapServers: "kafka.kafka.svc.cluster.local:9092"
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: PLAIN
            sasl.jaas.config: |
              org.apache.kafka.common.security.plain.PlainLoginModule required
                username="${KAFKA_USERNAME}"
                password="${KAFKA_PASSWORD}";
            client.dns.lookup: use_all_dns_ips
            request.timeout.ms: 45000
            socket.connection.setup.timeout.ms: 30000 
    # Optional but recommended
    metrics:
      enabled: true
      kafkaClusterName: "kafka-cluster"