apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka-ui
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kafka-ui-values
  values:
    env:
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: KAFKA_CLUSTERS_0_NAME
      value: "kafka-cluster"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka.kafka.svc.cluster.local:9092"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
      value: "SASL_PLAINTEXT"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
      value: "PLAIN"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_USERNAME
      value: "$KAFKA_USERNAME"                        
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_PASSWORD 
      value: "$KAFKA_PASSWORD"                        
    kafka:
      clusters:
        - name: kafka-cluster
          bootstrapServers: "kafka.kafka.svc.cluster.local:9092"
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: PLAIN
            sasl.username: ${KAFKA_USERNAME}
            sasl.password: ${KAFKA_PASSWORD}
    metrics:
      enabled: true
      kafkaClusterName: "kafka-cluster"