apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  interval: 1m
  path: ./infrastructure/kafka-ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kafka-ui  