apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-ui-secret
  namespace: kafka-ui
spec:
  encryptedData:
    KAFKA_PASSWORD: AgBkLm/OEPIM5C0PJZfTFB1zriLDsrR1VH+g0chSsnUb1JF1TL77mT9AKbfF35tBV9y+DnkkPzFNE3SQoGA6HAMeBCyN9FTPnzHZRO7popI9stm4atDXFe3ovtXa8/UwGHF5VEulsXnNQIQOQlEuSGMlzjF8deYRIgN$
    KAFKA_USERNAME: AgAsy+Tx7wAulSv0mD6bULBwRkMy1Qe8yACD4IZzkaWd4Cf3oWpX+urgfnbVPeDQlCVAysdpG7XuJVRbEJ5F1oLsey6wWRarPzOrppqDxWR9uBHzZ+mrjfeBf+17cqaCWJ4AhmUpLMx1daQcoDtspn2Ilc3Jy6dfo56$
  template:
    metadata:
      creationTimestamp: null
      name: kafka-ui-secret
      namespace: kafka-ui
    type: Opaque