apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-lb
  namespace: kafka-ui
  labels:
    app: kafka-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kafka-ui
