kafka:
  clusters:
    - name: kraft-cluster
      bootstrapServers: kafka-headless.kafka.svc.cluster.local:9092
      kafkaVersion: "3.6.0"
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

service:
  type: LoadBalancer
  port: 80
