env:
  - name: KAFKA_CLUSTERS_0_NAME
    value: "kafka-cluster"
  - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
    value: "kafka.kafka.svc.cluster.local:9092"
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
    value: "PLAINTEXT"
  - name: LOG_LEVEL
    value: "DEBUG"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
