apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: no-code-otel
  namespace: flux-system
resources:
  - postgresql-homelab-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml