apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/infrastructure/databases/elastic 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system