apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/nodejs/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default  