apiVersion: v1
kind: Service
metadata:
  name: dice-roll
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: dice-roll
  ports:
    - name: http
      port: 80
      targetPort: 8080