apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: no-code-otel
  namespace: flux-system
spec:
  targetNamespace: applications
  interval: 1m0s
  path: "./apps/elastic-otel"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster