apiVersion: v1
kind: Service
metadata:
  name: elastic-otel
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: elastic-otel
  ports:
    - name: http
      port: 80
      targetPort: 8080