apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-otel
  namespace: applications
spec:
  selector:
    matchLabels:
      app: elastic-otel
  template:
    metadata:
      labels:
        app: elastic-otel
    spec:
      containers:
      - name: elastic-otel
        image: ghcr.io/jaysuzi5/no-code-otel:v0.3.7
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-elastic.elasticsearch.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_SERVICE_NAME
          value: "elastic-no-code-otel"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: OTEL_LOG_LEVEL
          value: "error"
        - name: APP_LOG_LEVEL
          value: "ERROR"          
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgresql-homelab-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgresql-homelab-secret
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: elasticsearch-credentials
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: elasticsearch-credentials
        - name: ELASTIC_SERVER
          value: "https://elasticsearch-master.elasticsearch.svc.cluster.local:9200"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-credentials
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mongodb-credentials
        - name: MONGODB_HOST
          value: "mongodb.mongodb.svc.cluster.local:27017"
        - name: KAFKA_SERVER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: RANDOM_SERVICE_URL
          value: "http://elastic-otel.applications.svc.cluster.local/random"
        envFrom:
        - configMapRef:
            name: elastic-otel-config