apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: no-code-otel
  namespace: flux-system
resources:
  - elastic_secret.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml