---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-jcurtis
  namespace: postgresql
spec:
  encryptedData:
    password: AgCKKaRmUtjw+pTFDaVjZVPQp7bo2HhWLvkQPAYQ6xT33kDVcXUHtSkL42L4w4I4rPVcdA5UxaWOzqqvcv00jmZ62brlnCbi6ajPsZ0SUyaXnUk9FsolJeDU/c/sXudQwXEHjNOlV8GjaBQRltkHghovhg7wNsQG2QAx7DW11ZHomOcz0bk9ZopxCKYpkiIvy4hD/hZYGLXprn6vW1Lhg5qLCX041wCuXW4lzQCeZUK7KsWUaRtv2oiVCf/pknIIwCIvFdMCvlxxes2oNHSRpmztVquW+ehdbhYugZ/sNpNi3nXuQ8zX0iFa/TRXKl5LOd8aeZ9z1PZvjhPtWaGPNs274jqD/laFfjwSOJVqT6Mgi4twP1NRWaTRE1lS4slfmw6ThxxQW9agqOFFE9OVu3dFn2vNpuzuLx5RohzKkqdyqlnsoIFnEhxkp9+3oAIxTaZyWvfKhCf+QyfO0rU+xCCY12ozUzwxy/lQXn0+6QZuZ1IQ7dTqZzvCAz9PNCvS2B2S4Y+9Zl7CsMUnuDj2dUt9muw/+n+gnklDnDG/4Z2py/H9odZUVSD+Ax4lhSECJtzizKD4gDzTYhuO20ARDIgRaXi6ezlYIzWHNug9S4hjRiUwxyRVjJM87Sscm3ko4GfcGrZ9qSDTReMZSFiQ8jeX8q4F26CYdHGbIq4lcKi46SwPNVPIQ2EnP3/RVWE+bgDHp/M3V+n5Q1kJ1dtXwwctXNXDwC+hWsD+ul7wFCnzuHJDbNPPgAELJhKFnIVXfsdQWRsM4EogxgJg5EqqZAP3
    username: AgATmz/Co3eRXKH0PdluMx9yPRNkuGrb6NlG2/joa075QcAirsR1JIJKiklwZhewteoWQDf/2aDn4Kg/IWkAVCGquTSg3MM7KaQiaHvo//aG352OGX/UOVECBTmFSLvZB7BdP9zWxrMuD70HFU8OK6krY/Xk9pJntZi2NlhS14lLJ73qLvwblfQDIG7tTpsLYqYzF98qJMSqzzGFdaeG86+uy/9qCMTK/TEOkfDp46lAeR3w0H2Ya8jfvbqo/Fkol27ZDhL63nYVjmK3nwiWS2BB4itFXFs2WmNf14KjFCyvKLmNR1qtKOsyR92HUI0TG44M9VqXF5syN9zwgKjSG/1JffnVPJQe5Q9kBC3H90Ot3VwdjiVGnycb57DyUfAdZs84xpa/+6NfcUpRIx4rk48JYmI834mZ2QIpD1r29zHvc2ieiCJ5osKp3obQHEVwPcojPfVBQD0vq930Z69/YBLRFuNnt1l7ICQU6DLFcurBFyd2FybVCdYUMLeud4NbpPVwYB7EJzGt8Kb92u3JS/1l5+Z82Jv5QZ/DuSLxAYYG3aVErlVWKanoPrxCUpruTIfSqjCzD1Cea61vouKH/D23wUl4qv5pI3L87noLCSqKS+qoituqhD2X18EfJi0j/dJF7m3MgL8Dlia6iFT5YiTgtbl5pgmz0t3ZQhht/4TU8izIo2fqtHT3xWHcmGinNJA8nBSPvqlP
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-jcurtis
      namespace: postgresql
      labels:
        cnpg.io/reload: "true"
    type: kubernetes.io/basic-auth
