---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: postgresql
spec:
  encryptedData:
    password: AgA/egvSbyFU27S2x7UPwG0okYQR0j4JPrimmzRlkHo6vNrbfOk2w9y+2ZeoDevLOvPt2V2BDlVaaFQxb9/trIz7SZhN9eKUZdUOOdbvRu/59r+cPujUMzYkM2EUUy3jhpIDfd2YclG8ajNhGizXPto6fnURu1VcDSCGvrmHSlb0bdKjJF2IDBcZiwo5txnb7qTm2gcGb55nAlJorD1JCo5X6TtbW5yid4ol9bENe7oH4u4+i0dtYEltwdh+4eqDqp61ccJo3EBGdwWpyqdQ0bq2BOMA6FT1ubu8RluCZCkIk62icTwMygmB4tUcq3TAAl9R9J3BUxR23BnA5ClDg5s8HdjyDTND87X6ogA8J/vtFo3pW6P1cnCQX42jwHDz8vvyrmrSfq8aJcZk+y0k3Jvr1XgJEmcp1iMwUwa6GPsAjHzopNg8dJdNl/DYjhWLINPW46nvRLvSPJDnEgaMO69adO4hwL2oD0zZJSJJqEPiIBaNcestcGX7unGv9ZBZrIerRCHR8KadPB0yqAiyhkk3RRFTMTClODe+bAGFjE5GeLKtSPuuaHYgblatnU/XD5eYpnoIABwi4TuJPxoPVNSI5rBfx6bmruTN++GB0yvlU26cSvQW+Z627EyFjQIyQip9o/60Y2kNmmwhlxgjtZ/WDri+PEDNnIhDWuamV2Qb22lEMANFfZXDIrdbbFmq545+QVQZSVzQifxe8UTr
    username: AgBB7DKsAmjaIeZ+hq2xHHUa4nUhrYAZI1I9mt/0VgZdjc3ez1pgZZw8ZqzZQb5Ryk9q+tkakgyX6TjRTrpA1pawHHCB3MXJ/hNF6y9E/eL38qfFOqzGPaw5QBRtjU7znWV4v73nuz96WGUlET0miSLpO1znQqtJM4EkfDG1TPSNA5IZDHunkvR1IxQRAX96Lygbypq9pWxLgU/UyJcfoRv5JXlSUjDNIuSzzT6w5nv2SUaU+Kcn3YXVdqUXhOAU2FWIMR3kbreT04UgnXacIkCZ+z9lk6EFNi5YejfUoMpIb7I0/S4ZnCLjqR03LkKaA0RIwMoCw9uKfMWl7HQcnFIkQ50XtyYlinSGWB2jWwtksNORuya6jCuEjnRZsvglC8mpbc+wHa/7raMY/1St3iZyWRoq/wq2Ic90LGClFa+ZehehnK9OacRePLyk9LRy5IvoMibm/JGHCYSLcAdOcTVuU51aIMFrzwTNgeTpLe/UCF58VEikxkpWqs7qv7U6nEkiIdICNVGdK5QG7WJTDYQs9eYFVLau86uEI45xSy5d8OAHr1dX6sGroh54A5NMiHNWgI47v54t3owhJjxtQsosklRYJDn31ew1mxCKBqSqTkkdFUv5K4DvjSDHr2UUTMOBmi+OGtxISIQI9YEL5Ccp8sb4UpgYZ+KEKts6lv8NQzNACaa/137ZTPmWXIyeq6xvk4nb7lzk
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: postgresql
    type: Opaque
