apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: cluster.local/nfs-client-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql-homelab
spec:
  instances: 3
  storage:
    storageClass: "nfs-client"
    size: 10Gi
  bootstrap:
    initdb:
      database: homelab
  #     owner: jcurtis
  # users:
  #   - name: jcurtis
  #     secret:
  #       name: postgres-homelab-credentials
  # secrets:
  #   users:
  #     - name: jcurtis
  #       secret: postgres-homelab-credentials      
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster-external
  namespace: postgresql-homelab
  labels:
    app: postgresql-cluster
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgresql-cluster
    cnpg.io/instanceRole: primary
  # bootstrap:
  #   initdb:
  #     database: homelab
  #     owner: jcurtis
  # users:
  #   - name: jcurtis
  #     secret:
  #       name: postgres-homelab-credentials
  # secrets:
  #   users:
  #     - name: jcurtis
  #       secret: postgres-homelab-credentials
  # externalClusters:
  #   - name: clusterBackup
  #     barmanObjectStore:
  #       destinationPath: "https://hldatabaseproduction.blob.core.windows.net/linkding
  #       serverName: linkding-db-production-cnpg-v0
  #       azureCredentials:
  #         storageAccount:
  #           name: azure-creds
  #           key: linkding-storage-account-name
  #         storageSasToken:
  #           name: azure-creds
  #           key: linkding-blob-sas
  # backup:
  #   barmanObjectStore:
  #     destinationPath: https://hldatabaseproduction.blob.core.windows.net/linkding
  #     azureCredentials:
  #       storageAccount:
  #         name: azure-creds
  #         key: linkding-storage-account-name
  #       storageSasToken:
  #         name: azure-creds
  #         key: linkding-blob-sas
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip
  #   retentionPolicy: 14d

  # handy: resources can be used to trigger a redeploy
  # resources:
  #   requests:
  #     memory: 320Mi

  # managed:
  #   services:
  #     disabledDefaultServices:
  #       - ro
  #       - r
  #     additional:
  #       - selectorType: rw
  #         serviceTemplate:
  #           metadata:
  #             name: linkding-db-lb
  #             labels:
  #               cilium-lb-pool: postgres-pool
  #             annotations:
  #               external-dns.alpha.kubernetes.io/hostname: linkding-pg.mischavandenburg.net
  #           spec:
  #             type: LoadBalancer