apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-homelab-cluster
  namespace: postgresql-homelab
spec:
  description: Postgres cluster for the homelab database
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3
  inheritedMetadata:
    labels:
      app: homelab-database
      policy-type: "database"
  monitoring:
    enablePodMonitor: true
  storage:
    size: 3Gi
    storageClass: postgresql-homelab-storage
  bootstrap:
    initdb:
      database: homelab
      owner: jcurtis
  secrets:
    users:
      - name: jcurtis
        secret: postgres-homelab-credentials
  # externalClusters:
  #   - name: clusterBackup
  #     barmanObjectStore:
  #       destinationPath: "https://hldatabaseproduction.blob.core.windows.net/linkding
  #       serverName: linkding-db-production-cnpg-v0
  #       azureCredentials:
  #         storageAccount:
  #           name: azure-creds
  #           key: linkding-storage-account-name
  #         storageSasToken:
  #           name: azure-creds
  #           key: linkding-blob-sas
  # backup:
  #   barmanObjectStore:
  #     destinationPath: https://hldatabaseproduction.blob.core.windows.net/linkding
  #     azureCredentials:
  #       storageAccount:
  #         name: azure-creds
  #         key: linkding-storage-account-name
  #       storageSasToken:
  #         name: azure-creds
  #         key: linkding-blob-sas
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip
  #   retentionPolicy: 14d

  # handy: resources can be used to trigger a redeploy
  # resources:
  #   requests:
  #     memory: 320Mi

  # managed:
  #   services:
  #     disabledDefaultServices:
  #       - ro
  #       - r
  #     additional:
  #       - selectorType: rw
  #         serviceTemplate:
  #           metadata:
  #             name: linkding-db-lb
  #             labels:
  #               cilium-lb-pool: postgres-pool
  #             annotations:
  #               external-dns.alpha.kubernetes.io/hostname: linkding-pg.mischavandenburg.net
  #           spec:
  #             type: LoadBalancer